# Generated by Django 2.1.1 on 2018-09-27 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('entities_id', models.AutoField(primary_key=True, serialize=False)),
                ('entities_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('entities_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='用户名', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
