# Generated by Django 2.1.1 on 2018-09-27 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('World', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_notes', models.CharField(blank=True, max_length=108, verbose_name='注释')),
                ('entity_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '实体',
                'verbose_name_plural': '实体',
                'db_table': 'Entity',
            },
        ),
        migrations.CreateModel(
            name='Entity_RelationShip',
            fields=[
                ('er_id', models.AutoField(primary_key=True, serialize=False)),
                ('er_time', models.DateTimeField(auto_now_add=True)),
                ('er_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='实体', to='World.Entity')),
            ],
            options={
                'verbose_name': '实体-关系',
                'verbose_name_plural': '实体-关系',
                'db_table': 'ER',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=32, verbose_name='标签名')),
                ('label_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'Label',
            },
        ),
        migrations.CreateModel(
            name='RelationShip',
            fields=[
                ('relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_name', models.CharField(max_length=32)),
                ('relationship_entities', models.ManyToManyField(through='World.Entity_RelationShip', to='World.Entity')),
            ],
            options={
                'verbose_name': '关系',
                'verbose_name_plural': '关系',
                'db_table': 'RelationShip',
            },
        ),
        migrations.RemoveField(
            model_name='entities',
            name='entities_name',
        ),
        migrations.DeleteModel(
            name='Entities',
        ),
        migrations.AddField(
            model_name='entity_relationship',
            name='er_relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='关系', to='World.RelationShip'),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='标签', to='World.Label'),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='用户名', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
