# Generated by Django 2.1.1 on 2018-09-28 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0002_auto_20180927_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label_RelationShip',
            fields=[
                ('lr_id', models.AutoField(primary_key=True, serialize=False)),
                ('lr_time', models.DateTimeField(auto_now_add=True)),
                ('lr_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World.Label', verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签-关系',
                'verbose_name_plural': '标签-关系',
                'db_table': 'LR',
            },
        ),
        migrations.RemoveField(
            model_name='entity_relationship',
            name='er_entity',
        ),
        migrations.RemoveField(
            model_name='entity_relationship',
            name='er_relationship',
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World.Label', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_entities',
            field=models.ManyToManyField(through='World.Label_RelationShip', to='World.Label'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_name',
            field=models.CharField(max_length=32, verbose_name='关系'),
        ),
        migrations.DeleteModel(
            name='Entity_RelationShip',
        ),
        migrations.AddField(
            model_name='label_relationship',
            name='lr_relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='World.RelationShip', verbose_name='关系'),
        ),
    ]
