# Generated by Django 2.1.1 on 2018-09-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0004_auto_20180928_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='实体名称'),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='标签名'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='关系'),
        ),
    ]
