# Generated by Django 2.1.1 on 2018-10-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0005_auto_20180928_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity_color',
            field=models.CharField(blank=True, max_length=32, verbose_name='实体颜色'),
        ),
        migrations.AddField(
            model_name='label',
            name='label_color',
            field=models.CharField(blank=True, max_length=32, verbose_name='标签颜色'),
        ),
    ]
