# Generated by Django 2.1.1 on 2018-10-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('World', '0006_auto_20181008_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='label_hover_color',
            field=models.CharField(blank=True, max_length=32, verbose_name='标签hover颜色'),
        ),
    ]
